name: Rust (build)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'cli/**'
      - 'proto/**'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package Version"
        required: true
        default: "1.0.0"

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v1
      - run: |
          rustup install nightly
          rustup default nightly
          rustup component add rustfmt
          cargo build
          cargo test
