name: Build Documentation

on:
  # todo: add a staging target for doc builds
  # pull_request: 
  #   branches:
  #     - main
  #   paths:
  #     - 'docs/**'
  #     - 'mkdocs.yml'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install git+https://${{ secrets.MKDOCS_INSIDERS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install mkdocs-codeinclude-plugin
      - run: mkdocs gh-deploy --remote-branch gh-pages --site-dir ./docs-html --force

