# This action is used to manually invoke a full test against a certain environment
# Requires an endpoint input which you can get from the Pulumi outputs

name: Test Environment

on:
  workflow_dispatch:
    inputs:
      serverEndpoint:
        description: 'The endpoint of the server to test (ex. example.com)'
        required: true
        default: 'staging-internal.trinsic.cloud'
      serverPort:
        description: 'The service port of the endpoint (ex. 443)'
        required: true
        default: 443
      useTls:
        description: 'Indicates if TLS should be used'
        required: true
        default: true

jobs:
  test_infra:
    name: Run .NET SDK Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
      - run: |
          dotnet restore
          dotnet build -c Release
          dotnet test -c Release -v n
        working-directory: ./dotnet/
        env:
          TEST_SERVER_ENDPOINT: ${{ github.event.inputs.serverEndpoint }}
          TEST_SERVER_PORT: ${{ github.event.inputs.serverPort }}
          TEST_SERVER_USE_TLS: ${{ github.event.inputs.useTls }}